//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.296
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PanelImage.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PanelImage.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap button_quit_disable {
            get {
                object obj = ResourceManager.GetObject("button_quit_disable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap button_quit_enable {
            get {
                object obj = ResourceManager.GetObject("button_quit_enable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap button_quit_press {
            get {
                object obj = ResourceManager.GetObject("button_quit_press", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CommandPanel_HD1080 {
            get {
                object obj = ResourceManager.GetObject("CommandPanel_HD1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CommandPanel_SVGA {
            get {
                object obj = ResourceManager.GetObject("CommandPanel_SVGA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CommandPanel_SXGA {
            get {
                object obj = ResourceManager.GetObject("CommandPanel_SXGA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CommandPanel_WSXGAPlus {
            get {
                object obj = ResourceManager.GetObject("CommandPanel_WSXGAPlus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CommandPanel_XGA {
            get {
                object obj = ResourceManager.GetObject("CommandPanel_XGA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap InformationPanel_HD1080 {
            get {
                object obj = ResourceManager.GetObject("InformationPanel_HD1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap InformationPanel_SVGA {
            get {
                object obj = ResourceManager.GetObject("InformationPanel_SVGA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap InformationPanel_SXGA {
            get {
                object obj = ResourceManager.GetObject("InformationPanel_SXGA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap InformationPanel_WSXGAPlus {
            get {
                object obj = ResourceManager.GetObject("InformationPanel_WSXGAPlus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap InformationPanel_XGA {
            get {
                object obj = ResourceManager.GetObject("InformationPanel_XGA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap InformationTabPanel_HD1080 {
            get {
                object obj = ResourceManager.GetObject("InformationTabPanel_HD1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NavigationPanel_HD1080 {
            get {
                object obj = ResourceManager.GetObject("NavigationPanel_HD1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NavigationPanel_SVGA {
            get {
                object obj = ResourceManager.GetObject("NavigationPanel_SVGA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NavigationPanel_SXGA {
            get {
                object obj = ResourceManager.GetObject("NavigationPanel_SXGA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NavigationPanel_WSXGAPlus {
            get {
                object obj = ResourceManager.GetObject("NavigationPanel_WSXGAPlus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NavigationPanel_XGA {
            get {
                object obj = ResourceManager.GetObject("NavigationPanel_XGA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Subnav_disable {
            get {
                object obj = ResourceManager.GetObject("Subnav_disable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Subnav_enable {
            get {
                object obj = ResourceManager.GetObject("Subnav_enable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Subnav_press {
            get {
                object obj = ResourceManager.GetObject("Subnav_press", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SubnavPanel_HD1080 {
            get {
                object obj = ResourceManager.GetObject("SubnavPanel_HD1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SubnavPanel_SVGA {
            get {
                object obj = ResourceManager.GetObject("SubnavPanel_SVGA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SubnavPanel_SXGA {
            get {
                object obj = ResourceManager.GetObject("SubnavPanel_SXGA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SubnavPanel_WSXGAPlus {
            get {
                object obj = ResourceManager.GetObject("SubnavPanel_WSXGAPlus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SubnavPanel_XGA {
            get {
                object obj = ResourceManager.GetObject("SubnavPanel_XGA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TabnavPanel_HD1080 {
            get {
                object obj = ResourceManager.GetObject("TabnavPanel_HD1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TitlePanel_HD1080 {
            get {
                object obj = ResourceManager.GetObject("TitlePanel_HD1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TitlePanel_SVGA {
            get {
                object obj = ResourceManager.GetObject("TitlePanel_SVGA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TitlePanel_SXGA {
            get {
                object obj = ResourceManager.GetObject("TitlePanel_SXGA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TitlePanel_WSXGAPlus {
            get {
                object obj = ResourceManager.GetObject("TitlePanel_WSXGAPlus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TitlePanel_XGA {
            get {
                object obj = ResourceManager.GetObject("TitlePanel_XGA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
