//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.1008
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UEMScreen.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UEMScreen.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _1 {
            get {
                object obj = ResourceManager.GetObject("1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1__2_ {
            get {
                object obj = ResourceManager.GetObject("1 (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _10 {
            get {
                object obj = ResourceManager.GetObject("10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _11 {
            get {
                object obj = ResourceManager.GetObject("11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _12 {
            get {
                object obj = ResourceManager.GetObject("12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _121 {
            get {
                object obj = ResourceManager.GetObject("121", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _13 {
            get {
                object obj = ResourceManager.GetObject("13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _2 {
            get {
                object obj = ResourceManager.GetObject("2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _2__2_ {
            get {
                object obj = ResourceManager.GetObject("2 (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _2_1 {
            get {
                object obj = ResourceManager.GetObject("2-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _20120425123256_그래프 {
            get {
                object obj = ResourceManager.GetObject("20120425123256_그래프", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _3 {
            get {
                object obj = ResourceManager.GetObject("3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _3__2_ {
            get {
                object obj = ResourceManager.GetObject("3 (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _3__2_1 {
            get {
                object obj = ResourceManager.GetObject("3 (2)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _4 {
            get {
                object obj = ResourceManager.GetObject("4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _4__2_ {
            get {
                object obj = ResourceManager.GetObject("4 (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _4_1 {
            get {
                object obj = ResourceManager.GetObject("4-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _5 {
            get {
                object obj = ResourceManager.GetObject("5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _5__2_ {
            get {
                object obj = ResourceManager.GetObject("5 (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _5__2_1 {
            get {
                object obj = ResourceManager.GetObject("5 (2)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _5__2_2 {
            get {
                object obj = ResourceManager.GetObject("5 (2)2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _6 {
            get {
                object obj = ResourceManager.GetObject("6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _6__2_ {
            get {
                object obj = ResourceManager.GetObject("6 (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _6__2_1 {
            get {
                object obj = ResourceManager.GetObject("6 (2)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _6__2_2 {
            get {
                object obj = ResourceManager.GetObject("6 (2)2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _7 {
            get {
                object obj = ResourceManager.GetObject("7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _7__2_ {
            get {
                object obj = ResourceManager.GetObject("7 (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _8 {
            get {
                object obj = ResourceManager.GetObject("8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _8__2_ {
            get {
                object obj = ResourceManager.GetObject("8 (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _8__2_1 {
            get {
                object obj = ResourceManager.GetObject("8 (2)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _9 {
            get {
                object obj = ResourceManager.GetObject("9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _노랑_대 {
            get {
                object obj = ResourceManager.GetObject("(노랑)대", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _녹색_대 {
            get {
                object obj = ResourceManager.GetObject("(녹색)대", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _녹색_대1 {
            get {
                object obj = ResourceManager.GetObject("(녹색)대1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _빨강_대 {
            get {
                object obj = ResourceManager.GetObject("(빨강)대", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _빨강_대1 {
            get {
                object obj = ResourceManager.GetObject("(빨강)대1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _파랑_대 {
            get {
                object obj = ResourceManager.GetObject("(파랑)대", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HINGE {
            get {
                object obj = ResourceManager.GetObject("HINGE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap InformationPanel_HD1080 {
            get {
                object obj = ResourceManager.GetObject("InformationPanel_HD1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap InformationPanel_SXGA_for_EXT {
            get {
                object obj = ResourceManager.GetObject("InformationPanel_SXGA-for-EXT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap InformationPanel_SXGA_for_EXT1 {
            get {
                object obj = ResourceManager.GetObject("InformationPanel_SXGA-for-EXT1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap InformationTabPanel_HD1080 {
            get {
                object obj = ResourceManager.GetObject("InformationTabPanel_HD1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap InformationTabPanel_HD10801 {
            get {
                object obj = ResourceManager.GetObject("InformationTabPanel_HD10801", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kg_노랑_ {
            get {
                object obj = ResourceManager.GetObject("kg(노랑)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kg_녹색_ {
            get {
                object obj = ResourceManager.GetObject("kg(녹색)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kg_파랑_ {
            get {
                object obj = ResourceManager.GetObject("kg(파랑)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kg2_노랑_ {
            get {
                object obj = ResourceManager.GetObject("kg2(노랑)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kg2_노랑_1 {
            get {
                object obj = ResourceManager.GetObject("kg2(노랑)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kg2_노랑_2 {
            get {
                object obj = ResourceManager.GetObject("kg2(노랑)2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kg2_노랑_3 {
            get {
                object obj = ResourceManager.GetObject("kg2(노랑)3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kg2_노랑_4 {
            get {
                object obj = ResourceManager.GetObject("kg2(노랑)4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kg2_노랑_5 {
            get {
                object obj = ResourceManager.GetObject("kg2(노랑)5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kg2_녹색_ {
            get {
                object obj = ResourceManager.GetObject("kg2(녹색)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kg2_녹색_1 {
            get {
                object obj = ResourceManager.GetObject("kg2(녹색)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kg2_녹색_2 {
            get {
                object obj = ResourceManager.GetObject("kg2(녹색)2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kg2_녹색_3 {
            get {
                object obj = ResourceManager.GetObject("kg2(녹색)3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kg2_녹색_4 {
            get {
                object obj = ResourceManager.GetObject("kg2(녹색)4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kg2_녹색_5 {
            get {
                object obj = ResourceManager.GetObject("kg2(녹색)5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kg2_파랑_ {
            get {
                object obj = ResourceManager.GetObject("kg2(파랑)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kg2_파랑_1 {
            get {
                object obj = ResourceManager.GetObject("kg2(파랑)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kg2_파랑_2 {
            get {
                object obj = ResourceManager.GetObject("kg2(파랑)2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kg2_파랑_3 {
            get {
                object obj = ResourceManager.GetObject("kg2(파랑)3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kg2_파랑_4 {
            get {
                object obj = ResourceManager.GetObject("kg2(파랑)4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kg2_파랑_5 {
            get {
                object obj = ResourceManager.GetObject("kg2(파랑)5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kw_노랑_ {
            get {
                object obj = ResourceManager.GetObject("kw(노랑)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kw_녹색_ {
            get {
                object obj = ResourceManager.GetObject("kw(녹색)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kw_파랑_ {
            get {
                object obj = ResourceManager.GetObject("kw(파랑)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kw2_노랑_ {
            get {
                object obj = ResourceManager.GetObject("kw2(노랑)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kw2_노랑_1 {
            get {
                object obj = ResourceManager.GetObject("kw2(노랑)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kw2_노랑_2 {
            get {
                object obj = ResourceManager.GetObject("kw2(노랑)2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kw2_녹색_ {
            get {
                object obj = ResourceManager.GetObject("kw2(녹색)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kw2_녹색_1 {
            get {
                object obj = ResourceManager.GetObject("kw2(녹색)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kw2_녹색_2 {
            get {
                object obj = ResourceManager.GetObject("kw2(녹색)2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kw2_파랑_ {
            get {
                object obj = ResourceManager.GetObject("kw2(파랑)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kw2_파랑_1 {
            get {
                object obj = ResourceManager.GetObject("kw2(파랑)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kw2_파랑_2 {
            get {
                object obj = ResourceManager.GetObject("kw2(파랑)2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap m3_노랑_ {
            get {
                object obj = ResourceManager.GetObject("m3(노랑)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap m3_녹색_ {
            get {
                object obj = ResourceManager.GetObject("m3(녹색)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap m3_파랑_ {
            get {
                object obj = ResourceManager.GetObject("m3(파랑)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap m32_노랑_ {
            get {
                object obj = ResourceManager.GetObject("m32(노랑)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap m32_노랑_1 {
            get {
                object obj = ResourceManager.GetObject("m32(노랑)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap m32_노랑_2 {
            get {
                object obj = ResourceManager.GetObject("m32(노랑)2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap m32_녹색_ {
            get {
                object obj = ResourceManager.GetObject("m32(녹색)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap m32_녹색_1 {
            get {
                object obj = ResourceManager.GetObject("m32(녹색)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap m32_녹색_2 {
            get {
                object obj = ResourceManager.GetObject("m32(녹색)2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap m32_파랑_ {
            get {
                object obj = ResourceManager.GetObject("m32(파랑)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap m32_파랑_1 {
            get {
                object obj = ResourceManager.GetObject("m32(파랑)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap m32_파랑_2 {
            get {
                object obj = ResourceManager.GetObject("m32(파랑)2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap m3Ton_노랑_ {
            get {
                object obj = ResourceManager.GetObject("m3Ton(노랑)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap m3Ton_녹색_ {
            get {
                object obj = ResourceManager.GetObject("m3Ton(녹색)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap m3Ton_파랑_ {
            get {
                object obj = ResourceManager.GetObject("m3Ton(파랑)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap m3Ton2_노랑_ {
            get {
                object obj = ResourceManager.GetObject("m3Ton2(노랑)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap m3Ton2_노랑_1 {
            get {
                object obj = ResourceManager.GetObject("m3Ton2(노랑)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap m3Ton2_노랑_2 {
            get {
                object obj = ResourceManager.GetObject("m3Ton2(노랑)2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap m3Ton2_녹색_ {
            get {
                object obj = ResourceManager.GetObject("m3Ton2(녹색)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap m3Ton2_녹색_1 {
            get {
                object obj = ResourceManager.GetObject("m3Ton2(녹색)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap m3Ton2_녹색_2 {
            get {
                object obj = ResourceManager.GetObject("m3Ton2(녹색)2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap m3Ton2_파랑_ {
            get {
                object obj = ResourceManager.GetObject("m3Ton2(파랑)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap m3Ton2_파랑_1 {
            get {
                object obj = ResourceManager.GetObject("m3Ton2(파랑)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap m3Ton2_파랑_2 {
            get {
                object obj = ResourceManager.GetObject("m3Ton2(파랑)2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PIPE_ANGLE_BOTTOM_LEFT_DYellow {
            get {
                object obj = ResourceManager.GetObject("PIPE-ANGLE-BOTTOM-LEFT-DYellow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PIPE_ANGLE_BOTTOM_LEFT_OFF {
            get {
                object obj = ResourceManager.GetObject("PIPE-ANGLE-BOTTOM-LEFT-OFF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PIPE_ANGLE_BOTTOM_LEFT_OFF1 {
            get {
                object obj = ResourceManager.GetObject("PIPE-ANGLE-BOTTOM-LEFT-OFF1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PIPE_ANGLE_BOTTOM_RIGHT_DYellow {
            get {
                object obj = ResourceManager.GetObject("PIPE-ANGLE-BOTTOM-RIGHT-DYellow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PIPE_ANGLE_BOTTOM_RIGHT_OFF {
            get {
                object obj = ResourceManager.GetObject("PIPE-ANGLE-BOTTOM-RIGHT-OFF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PIPE_ANGLE_BOTTOM_RIGHT_OFF1 {
            get {
                object obj = ResourceManager.GetObject("PIPE-ANGLE-BOTTOM-RIGHT-OFF1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PIPE_ANGLE_TOP_LEFT_DYellow {
            get {
                object obj = ResourceManager.GetObject("PIPE-ANGLE-TOP-LEFT-DYellow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PIPE_ANGLE_TOP_LEFT_OFF {
            get {
                object obj = ResourceManager.GetObject("PIPE-ANGLE-TOP-LEFT-OFF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PIPE_ANGLE_TOP_LEFT_OFF1 {
            get {
                object obj = ResourceManager.GetObject("PIPE-ANGLE-TOP-LEFT-OFF1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PIPE_ANGLE_TOP_LEFT_OFF2 {
            get {
                object obj = ResourceManager.GetObject("PIPE-ANGLE-TOP-LEFT-OFF2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PIPE_ANGLE_TOP_RIGHT_DYellow {
            get {
                object obj = ResourceManager.GetObject("PIPE-ANGLE-TOP-RIGHT-DYellow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PIPE_ANGLE_TOP_RIGHT_OFF {
            get {
                object obj = ResourceManager.GetObject("PIPE-ANGLE-TOP-RIGHT-OFF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PIPE_BRANCH_TO_BOTTOM_DYELLOW {
            get {
                object obj = ResourceManager.GetObject("PIPE-BRANCH-TO-BOTTOM-DYELLOW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PIPE_BRANCH_TO_BOTTOM_OFF {
            get {
                object obj = ResourceManager.GetObject("PIPE-BRANCH-TO-BOTTOM-OFF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PIPE_BRANCH_TO_BOTTOM_OFF1 {
            get {
                object obj = ResourceManager.GetObject("PIPE-BRANCH-TO-BOTTOM-OFF1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PIPE_BRANCH_TO_BOTTOM_OFF2 {
            get {
                object obj = ResourceManager.GetObject("PIPE-BRANCH-TO-BOTTOM-OFF2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PIPE_BRANCH_TO_LEFT_DYELLOW {
            get {
                object obj = ResourceManager.GetObject("PIPE-BRANCH-TO-LEFT-DYELLOW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PIPE_BRANCH_TO_LEFT_OFF {
            get {
                object obj = ResourceManager.GetObject("PIPE-BRANCH-TO-LEFT-OFF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PIPE_BRANCH_TO_LEFT_OFF1 {
            get {
                object obj = ResourceManager.GetObject("PIPE-BRANCH-TO-LEFT-OFF1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PIPE_BRANCH_TO_RIGHT_DYELLOW {
            get {
                object obj = ResourceManager.GetObject("PIPE-BRANCH-TO-RIGHT-DYELLOW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PIPE_BRANCH_TO_RIGHT_OFF {
            get {
                object obj = ResourceManager.GetObject("PIPE-BRANCH-TO-RIGHT-OFF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PIPE_BRANCH_TO_TOP_DYELLOW {
            get {
                object obj = ResourceManager.GetObject("PIPE-BRANCH-TO-TOP-DYELLOW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PIPE_BRANCH_TO_TOP_OFF {
            get {
                object obj = ResourceManager.GetObject("PIPE-BRANCH-TO-TOP-OFF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PIPE_STRAIGHT_HORIZ_DYELLOW {
            get {
                object obj = ResourceManager.GetObject("PIPE-STRAIGHT-HORIZ-DYELLOW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PIPE_STRAIGHT_HORIZ_OFF {
            get {
                object obj = ResourceManager.GetObject("PIPE-STRAIGHT-HORIZ-OFF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PIPE_STRAIGHT_VERT_DYELLOW {
            get {
                object obj = ResourceManager.GetObject("PIPE-STRAIGHT-VERT-DYELLOW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PIPE_STRAIGHT_VERT_OFF {
            get {
                object obj = ResourceManager.GetObject("PIPE-STRAIGHT-VERT-OFF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap png_regulator_250x250 {
            get {
                object obj = ResourceManager.GetObject("png-regulator-250x250", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PressureGauge {
            get {
                object obj = ResourceManager.GetObject("PressureGauge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Printer {
            get {
                object obj = ResourceManager.GetObject("Printer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Printer1 {
            get {
                object obj = ResourceManager.GetObject("Printer1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TitlePanel_SXGA___for_EXT {
            get {
                object obj = ResourceManager.GetObject("TitlePanel_SXGA - for-EXT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap traducer_00 {
            get {
                object obj = ResourceManager.GetObject("traducer-00", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap traducer_001 {
            get {
                object obj = ResourceManager.GetObject("traducer-001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UBI {
            get {
                object obj = ResourceManager.GetObject("UBI", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 가스_빨강_ {
            get {
                object obj = ResourceManager.GetObject("가스(빨강)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 가스_빨강_1 {
            get {
                object obj = ResourceManager.GetObject("가스(빨강)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 가스_빨강_2 {
            get {
                object obj = ResourceManager.GetObject("가스(빨강)2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 가스량1_빨강_ {
            get {
                object obj = ResourceManager.GetObject("가스량1(빨강)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 대차이미지_전진 {
            get {
                object obj = ResourceManager.GetObject("대차이미지 전진", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 대차이미지_후진 {
            get {
                object obj = ResourceManager.GetObject("대차이미지 후진", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 대차이미지없음 {
            get {
                object obj = ResourceManager.GetObject("대차이미지없음", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 도면파트1 {
            get {
                object obj = ResourceManager.GetObject("도면파트1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 도면파트2 {
            get {
                object obj = ResourceManager.GetObject("도면파트2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 도면파트3 {
            get {
                object obj = ResourceManager.GetObject("도면파트3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 도면파트31 {
            get {
                object obj = ResourceManager.GetObject("도면파트31", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 도면파트6 {
            get {
                object obj = ResourceManager.GetObject("도면파트6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 도면파트7 {
            get {
                object obj = ResourceManager.GetObject("도면파트7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 도면파트8 {
            get {
                object obj = ResourceManager.GetObject("도면파트8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 버너불꽃 {
            get {
                object obj = ResourceManager.GetObject("버너불꽃", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 버튼이미지_그리드뷰 {
            get {
                object obj = ResourceManager.GetObject("버튼이미지-그리드뷰", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 불꽃1 {
            get {
                object obj = ResourceManager.GetObject("불꽃1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 불꽃11 {
            get {
                object obj = ResourceManager.GetObject("불꽃11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 불꽃2 {
            get {
                object obj = ResourceManager.GetObject("불꽃2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 불꽃2_1 {
            get {
                object obj = ResourceManager.GetObject("불꽃2-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 불꽃2_아래로 {
            get {
                object obj = ResourceManager.GetObject("불꽃2-아래로", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 불꽃21 {
            get {
                object obj = ResourceManager.GetObject("불꽃21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 불꽃3 {
            get {
                object obj = ResourceManager.GetObject("불꽃3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 불꽃31 {
            get {
                object obj = ResourceManager.GetObject("불꽃31", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 생산현황 {
            get {
                object obj = ResourceManager.GetObject("생산현황", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 생산현황_타이틀 {
            get {
                object obj = ResourceManager.GetObject("생산현황 타이틀", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 생산현황1 {
            get {
                object obj = ResourceManager.GetObject("생산현황1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 생산현황단위제거 {
            get {
                object obj = ResourceManager.GetObject("생산현황단위제거", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 세아메카닉스_로고3 {
            get {
                object obj = ResourceManager.GetObject("세아메카닉스 로고3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 세아조립 {
            get {
                object obj = ResourceManager.GetObject("세아조립", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 세아조립_1 {
            get {
                object obj = ResourceManager.GetObject("세아조립-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 세아조립1 {
            get {
                object obj = ResourceManager.GetObject("세아조립1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 쇳물 {
            get {
                object obj = ResourceManager.GetObject("쇳물", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 쇳물1 {
            get {
                object obj = ResourceManager.GetObject("쇳물1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 쇳물11 {
            get {
                object obj = ResourceManager.GetObject("쇳물11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 쇳물2 {
            get {
                object obj = ResourceManager.GetObject("쇳물2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 쇳물21 {
            get {
                object obj = ResourceManager.GetObject("쇳물21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 스크랩_빨강_ {
            get {
                object obj = ResourceManager.GetObject("스크랩(빨강)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 스크랩2_빨강_ {
            get {
                object obj = ResourceManager.GetObject("스크랩2(빨강)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 스크랩2_빨강_1 {
            get {
                object obj = ResourceManager.GetObject("스크랩2(빨강)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 스크랩2_빨강_2 {
            get {
                object obj = ResourceManager.GetObject("스크랩2(빨강)2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 스크랩엘레베이터 {
            get {
                object obj = ResourceManager.GetObject("스크랩엘레베이터", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 스크랩엘레베이터_down {
            get {
                object obj = ResourceManager.GetObject("스크랩엘레베이터-down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 스크랩엘레베이터_up {
            get {
                object obj = ResourceManager.GetObject("스크랩엘레베이터-up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 시간단위_파랑_ {
            get {
                object obj = ResourceManager.GetObject("시간단위(파랑)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 시간단위2_파랑_ {
            get {
                object obj = ResourceManager.GetObject("시간단위2(파랑)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 시간단위2_파랑_1 {
            get {
                object obj = ResourceManager.GetObject("시간단위2(파랑)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 시간단위2_파랑_2 {
            get {
                object obj = ResourceManager.GetObject("시간단위2(파랑)2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 안전벨브우 {
            get {
                object obj = ResourceManager.GetObject("안전벨브우", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 에너지_효율관리_시스템_레드_ {
            get {
                object obj = ResourceManager.GetObject("에너지 효율관리 시스템(레드)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 에너지_효율관리_시스템_레드_1 {
            get {
                object obj = ResourceManager.GetObject("에너지 효율관리 시스템(레드)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 엘레베이터도어C1 {
            get {
                object obj = ResourceManager.GetObject("엘레베이터도어C1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 엘레베이터도어O1 {
            get {
                object obj = ResourceManager.GetObject("엘레베이터도어O1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 연한노랑 {
            get {
                object obj = ResourceManager.GetObject("연한노랑", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 연한녹색 {
            get {
                object obj = ResourceManager.GetObject("연한녹색", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 연한분홍 {
            get {
                object obj = ResourceManager.GetObject("연한분홍", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 연한적색 {
            get {
                object obj = ResourceManager.GetObject("연한적색", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 연한적색1 {
            get {
                object obj = ResourceManager.GetObject("연한적색1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 용탕_기준 {
            get {
                object obj = ResourceManager.GetObject("용탕 기준", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 용탕_풀 {
            get {
                object obj = ResourceManager.GetObject("용탕 풀", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 월단위_노랑_ {
            get {
                object obj = ResourceManager.GetObject("월단위(노랑)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 월단위2_노랑_ {
            get {
                object obj = ResourceManager.GetObject("월단위2(노랑)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 월단위2_노랑_1 {
            get {
                object obj = ResourceManager.GetObject("월단위2(노랑)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 월단위2_노랑_2 {
            get {
                object obj = ResourceManager.GetObject("월단위2(노랑)2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 월단위2_노랑_3 {
            get {
                object obj = ResourceManager.GetObject("월단위2(노랑)3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 이미지_라벨바탕_청색 {
            get {
                object obj = ResourceManager.GetObject("이미지-라벨바탕-청색", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 이미지_바탕배경 {
            get {
                object obj = ResourceManager.GetObject("이미지-바탕배경", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 이미지_바탕배경1 {
            get {
                object obj = ResourceManager.GetObject("이미지-바탕배경1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 이미지_투명이미지 {
            get {
                object obj = ResourceManager.GetObject("이미지-투명이미지", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 이미지_펌프_프레임_바탕배경 {
            get {
                object obj = ResourceManager.GetObject("이미지-펌프-프레임-바탕배경", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 이미지_펌프on {
            get {
                object obj = ResourceManager.GetObject("이미지-펌프on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 이미지_화면아이콘_가스플로우 {
            get {
                object obj = ResourceManager.GetObject("이미지-화면아이콘-가스플로우", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 이미지_화면아이콘_가스플로우1 {
            get {
                object obj = ResourceManager.GetObject("이미지-화면아이콘-가스플로우1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 이미지off {
            get {
                object obj = ResourceManager.GetObject("이미지off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 이미지on {
            get {
                object obj = ResourceManager.GetObject("이미지on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 이미지on1 {
            get {
                object obj = ResourceManager.GetObject("이미지on1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 이미지unknown {
            get {
                object obj = ResourceManager.GetObject("이미지unknown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 인고트_빨강_ {
            get {
                object obj = ResourceManager.GetObject("인고트(빨강)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 인고트2_빨강_ {
            get {
                object obj = ResourceManager.GetObject("인고트2(빨강)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 인고트2_빨강_1 {
            get {
                object obj = ResourceManager.GetObject("인고트2(빨강)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 인고트2_빨강_2 {
            get {
                object obj = ResourceManager.GetObject("인고트2(빨강)2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 인고트2_빨강_3 {
            get {
                object obj = ResourceManager.GetObject("인고트2(빨강)3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 일단위_녹색_ {
            get {
                object obj = ResourceManager.GetObject("일단위(녹색)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 일단위2_녹색_ {
            get {
                object obj = ResourceManager.GetObject("일단위2(녹색)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 일단위2_녹색_1 {
            get {
                object obj = ResourceManager.GetObject("일단위2(녹색)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 일단위2_녹색_2 {
            get {
                object obj = ResourceManager.GetObject("일단위2(녹색)2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 장비1 {
            get {
                object obj = ResourceManager.GetObject("장비1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 장비11 {
            get {
                object obj = ResourceManager.GetObject("장비11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 장비12 {
            get {
                object obj = ResourceManager.GetObject("장비12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 장비투명 {
            get {
                object obj = ResourceManager.GetObject("장비투명", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 전력량_빨강_ {
            get {
                object obj = ResourceManager.GetObject("전력량(빨강)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 전력량2_빨강_ {
            get {
                object obj = ResourceManager.GetObject("전력량2(빨강)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 전력량2_빨강_1 {
            get {
                object obj = ResourceManager.GetObject("전력량2(빨강)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 전력량2_빨강_2 {
            get {
                object obj = ResourceManager.GetObject("전력량2(빨강)2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 진한주황 {
            get {
                object obj = ResourceManager.GetObject("진한주황", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 총_투입량_빨강_ {
            get {
                object obj = ResourceManager.GetObject("총 투입량(빨강)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이미지_BELLOWS {
            get {
                object obj = ResourceManager.GetObject("투명이미지-BELLOWS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이미지_regulator_250x250 {
            get {
                object obj = ResourceManager.GetObject("투명이미지-regulator-250x250", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이미지_regulator_250x2501 {
            get {
                object obj = ResourceManager.GetObject("투명이미지-regulator-250x2501", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이미지_scrap_elevator_cart_대칭 {
            get {
                object obj = ResourceManager.GetObject("투명이미지-scrap-elevator-cart-대칭", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이미지_scrap_elevator_frame_대칭 {
            get {
                object obj = ResourceManager.GetObject("투명이미지-scrap-elevator-frame-대칭", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이미지_tower_body_blue {
            get {
                object obj = ResourceManager.GetObject("투명이미지-tower-body-blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이미지_tower_door_BLUE {
            get {
                object obj = ResourceManager.GetObject("투명이미지-tower-door-BLUE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이미지_tower_door_BLUE_open {
            get {
                object obj = ResourceManager.GetObject("투명이미지-tower-door-BLUE-open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이미지_tower_door_GRA_open {
            get {
                object obj = ResourceManager.GetObject("투명이미지-tower-door-GRA-open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이미지_tower_door_GRA_open1 {
            get {
                object obj = ResourceManager.GetObject("투명이미지-tower-door-GRA-open1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이미지_tower_door_GRAY {
            get {
                object obj = ResourceManager.GetObject("투명이미지-tower-door-GRAY", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이미지_tower_door_open_green {
            get {
                object obj = ResourceManager.GetObject("투명이미지-tower-door-open-green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이미지_tower_door_open_green_open {
            get {
                object obj = ResourceManager.GetObject("투명이미지-tower-door-open-green-open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이미지_tower_door_red {
            get {
                object obj = ResourceManager.GetObject("투명이미지-tower-door-red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이미지_tower_middle_blue {
            get {
                object obj = ResourceManager.GetObject("투명이미지-tower-middle-blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이미지_매뉴얼밸브_녹색_sideview_open {
            get {
                object obj = ResourceManager.GetObject("투명이미지-매뉴얼밸브-녹색-sideview-open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이미지_매뉴얼밸브_녹색_sideview_open1 {
            get {
                object obj = ResourceManager.GetObject("투명이미지-매뉴얼밸브-녹색-sideview-open1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이미지_매뉴얼밸브_녹색_sideview_open2 {
            get {
                object obj = ResourceManager.GetObject("투명이미지-매뉴얼밸브-녹색-sideview-open2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이미지_매뉴얼밸브_녹색_sideview_open3 {
            get {
                object obj = ResourceManager.GetObject("투명이미지-매뉴얼밸브-녹색-sideview-open3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이미지_매뉴얼밸브_회색_sideview_open {
            get {
                object obj = ResourceManager.GetObject("투명이미지-매뉴얼밸브-회색-sideview-open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이미지_매뉴얼밸브_회색_sideview_open1 {
            get {
                object obj = ResourceManager.GetObject("투명이미지-매뉴얼밸브-회색-sideview-open1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이미지_매뉴얼밸브_회색_sideview_open2 {
            get {
                object obj = ResourceManager.GetObject("투명이미지-매뉴얼밸브-회색-sideview-open2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이미지_매뉴얼밸브_회색1_topview_close {
            get {
                object obj = ResourceManager.GetObject("투명이미지-매뉴얼밸브-회색1-topview-close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이미지_매뉴얼밸브_회색1_topview_close1 {
            get {
                object obj = ResourceManager.GetObject("투명이미지-매뉴얼밸브-회색1-topview-close1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이미지_버너수평 {
            get {
                object obj = ResourceManager.GetObject("투명이미지-버너수평", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이미지_버튼__파랑_대 {
            get {
                object obj = ResourceManager.GetObject("투명이미지-버튼 (파랑)대", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이미지_버튼용_glossy_long_website_buttons {
            get {
                object obj = ResourceManager.GetObject("투명이미지-버튼용-glossy_long_website_buttons", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이미지_세아용_박스 {
            get {
                object obj = ResourceManager.GetObject("투명이미지-세아용 박스", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이미지_신진로CI_회사명포함 {
            get {
                object obj = ResourceManager.GetObject("투명이미지-신진로CI-회사명포함", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이미지_압력게이지 {
            get {
                object obj = ResourceManager.GetObject("투명이미지-압력게이지", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이미지_엘레베이터_빈화면 {
            get {
                object obj = ResourceManager.GetObject("투명이미지-엘레베이터-빈화면", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이미지_엘레베이터C {
            get {
                object obj = ResourceManager.GetObject("투명이미지-엘레베이터C", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이미지_엘레베이터O {
            get {
                object obj = ResourceManager.GetObject("투명이미지-엘레베이터O", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이미지_용광로_기준레벨 {
            get {
                object obj = ResourceManager.GetObject("투명이미지-용광로-기준레벨", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이미지_용광로_비어있는 {
            get {
                object obj = ResourceManager.GetObject("투명이미지-용광로-비어있는", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이미지_용광로_풀레벨 {
            get {
                object obj = ResourceManager.GetObject("투명이미지-용광로-풀레벨", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이미지_용광로_풀레벨1 {
            get {
                object obj = ResourceManager.GetObject("투명이미지-용광로-풀레벨1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이미지_용광로_풀레벨2 {
            get {
                object obj = ResourceManager.GetObject("투명이미지-용광로-풀레벨2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이미지_용광로_하단_H빔 {
            get {
                object obj = ResourceManager.GetObject("투명이미지-용광로-하단-H빔", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이미지_용광로만 {
            get {
                object obj = ResourceManager.GetObject("투명이미지-용광로만", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이미지_이대리_교육용 {
            get {
                object obj = ResourceManager.GetObject("투명이미지-이대리 교육용", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이미지_펌프_on {
            get {
                object obj = ResourceManager.GetObject("투명이미지-펌프-on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이미지_펌프_on_회전 {
            get {
                object obj = ResourceManager.GetObject("투명이미지-펌프-on-회전", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이미지_펌프_unknown {
            get {
                object obj = ResourceManager.GetObject("투명이미지-펌프-unknown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이미지_펌프_unknown1 {
            get {
                object obj = ResourceManager.GetObject("투명이미지-펌프-unknown1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이미지_펌프_프레임_청색 {
            get {
                object obj = ResourceManager.GetObject("투명이미지-펌프-프레임-청색", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이미지_펌프_프레임_청색1 {
            get {
                object obj = ResourceManager.GetObject("투명이미지-펌프-프레임-청색1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이미지_펌프_프레임_청색2 {
            get {
                object obj = ResourceManager.GetObject("투명이미지-펌프-프레임-청색2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이미지_프로펠러on_붉은색 {
            get {
                object obj = ResourceManager.GetObject("투명이미지-프로펠러on-붉은색", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이미지_프로펠러on_붉은색회전 {
            get {
                object obj = ResourceManager.GetObject("투명이미지-프로펠러on-붉은색회전", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이미지_프로펠러unknown {
            get {
                object obj = ResourceManager.GetObject("투명이미지-프로펠러unknown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이미지_프로펠러unknown1 {
            get {
                object obj = ResourceManager.GetObject("투명이미지-프로펠러unknown1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이미지_힌지_청색 {
            get {
                object obj = ResourceManager.GetObject("투명이미지-힌지-청색", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이지미_tower_body_gray {
            get {
                object obj = ResourceManager.GetObject("투명이지미-tower-body-gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이지미_tower_body_gray_dark {
            get {
                object obj = ResourceManager.GetObject("투명이지미-tower-body-gray-dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이지미_tower_body_gray_dark1 {
            get {
                object obj = ResourceManager.GetObject("투명이지미-tower-body-gray-dark1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이지미_tower_body_gray_middle {
            get {
                object obj = ResourceManager.GetObject("투명이지미-tower-body-gray-middle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이지미_tower_body_gray_middle1 {
            get {
                object obj = ResourceManager.GetObject("투명이지미-tower-body-gray-middle1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이지미_tower_body_gray_middle10 {
            get {
                object obj = ResourceManager.GetObject("투명이지미-tower-body-gray-middle10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이지미_tower_body_gray_middle2 {
            get {
                object obj = ResourceManager.GetObject("투명이지미-tower-body-gray-middle2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이지미_tower_body_gray_middle3 {
            get {
                object obj = ResourceManager.GetObject("투명이지미-tower-body-gray-middle3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이지미_tower_body_gray_middle4 {
            get {
                object obj = ResourceManager.GetObject("투명이지미-tower-body-gray-middle4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이지미_tower_body_gray_middle5 {
            get {
                object obj = ResourceManager.GetObject("투명이지미-tower-body-gray-middle5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이지미_tower_body_gray_middle6 {
            get {
                object obj = ResourceManager.GetObject("투명이지미-tower-body-gray-middle6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이지미_tower_body_gray_middle7 {
            get {
                object obj = ResourceManager.GetObject("투명이지미-tower-body-gray-middle7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이지미_tower_body_gray_middle8 {
            get {
                object obj = ResourceManager.GetObject("투명이지미-tower-body-gray-middle8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이지미_tower_body_gray_middle9 {
            get {
                object obj = ResourceManager.GetObject("투명이지미-tower-body-gray-middle9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이지미_tower_body_gray1 {
            get {
                object obj = ResourceManager.GetObject("투명이지미-tower-body-gray1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이지미_인고트_8열 {
            get {
                object obj = ResourceManager.GetObject("투명이지미-인고트-8열", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 투명이지미_인고트_8열1 {
            get {
                object obj = ResourceManager.GetObject("투명이지미-인고트-8열1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 품명_빨강_ {
            get {
                object obj = ResourceManager.GetObject("품명(빨강)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 품명2_빨강_ {
            get {
                object obj = ResourceManager.GetObject("품명2(빨강)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 품명2_빨강_1 {
            get {
                object obj = ResourceManager.GetObject("품명2(빨강)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 품명2_빨강_2 {
            get {
                object obj = ResourceManager.GetObject("품명2(빨강)2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
